# Generated by Django 2.2 on 2020-06-11 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='description',
            name='course',
        ),
        migrations.AddField(
            model_name='course',
            name='description',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, related_name='of_course', to='courses.Description'),
            preserve_default=False,
        ),
    ]
